/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoveriesRouteImport } from './routes/discoveries'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveriesRoute = DiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discoveries': typeof DiscoveriesRoute
  '/gates': typeof GatesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/receipts': typeof ReceiptsRoute
  '/repositories': typeof RepositoriesRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discoveries': typeof DiscoveriesRoute
  '/gates': typeof GatesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/receipts': typeof ReceiptsRoute
  '/repositories': typeof RepositoriesRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discoveries': typeof DiscoveriesRoute
  '/gates': typeof GatesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/receipts': typeof ReceiptsRoute
  '/repositories': typeof RepositoriesRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discoveries'
    | '/gates'
    | '/login'
    | '/overview'
    | '/receipts'
    | '/repositories'
    | '/verify'
    | '/workspace'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discoveries'
    | '/gates'
    | '/login'
    | '/overview'
    | '/receipts'
    | '/repositories'
    | '/verify'
    | '/workspace'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/discoveries'
    | '/gates'
    | '/login'
    | '/overview'
    | '/receipts'
    | '/repositories'
    | '/verify'
    | '/workspace'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveriesRoute: typeof DiscoveriesRoute
  GatesRoute: typeof GatesRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RepositoriesRoute: typeof RepositoriesRoute
  VerifyRoute: typeof VerifyRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discoveries': {
      id: '/discoveries'
      path: '/discoveries'
      fullPath: '/discoveries'
      preLoaderRoute: typeof DiscoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveriesRoute: DiscoveriesRoute,
  GatesRoute: GatesRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ReceiptsRoute: ReceiptsRoute,
  RepositoriesRoute: RepositoriesRoute,
  VerifyRoute: VerifyRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
